jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout v4.1.7

      - name: Login to Docker Hub
        uses: docker/login-actionv3
        with:
          username: ${{ secrets.DOCKERHUB USERNAME }}
          password: ${{ secrets.DOCKERHUB TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./pasta_repositorio
          push: true
          tags: user/app:latest
